server:
  port: 9296
  
  
spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TinThuZarAye-TTZA-github/Microservice-SpringBoot-SpringCloud
          clone-on-start: true
        enabled: true 
        
     